fix: impure

diff --git a/.github/workflows/devenv.yaml b/.github/workflows/devenv.yaml
--- a/.github/workflows/devenv.yaml
+++ b/.github/workflows/devenv.yaml
@@ -1,7 +1,8 @@
 ---
 name: Devenv
 
-on:
+# prettier-ignore
+on:  # yamllint disable-line rule:truthy
   push:
     branches:
       - trunk
@@ -12,23 +13,31 @@ on:
     paths:
       - .github/workflows/devenv.yaml
       - devenv.nix
-      - flake.lock
+      - devenv.yaml
+      - devenv.lock
+      - devenv/**
       - flake.nix
+      - flake.lock
       - nix/devshells/**
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 permissions:
-  contents: read
-  packages: read
-  pull-requests: read
-  statuses: read
+  contents: write
+  packages: write
+  pull-requests: write
+  statuses: write
 
 env:
-  NIXPKGS_ALLOW_UNFREE: 1
-
+  # GitHub
   PROJECT: ${{ github.repository }}
-
   BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
   BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}
+
+  # Nix
+  NIXPKGS_ALLOW_UNFREE: 1
 
 defaults:
   run:
@@ -44,7 +53,7 @@ jobs:
 
     runs-on: ${{ matrix.os }}
 
-    timeout-minutes: 30
+    timeout-minutes: 60
     continue-on-error: false
 
     strategy:
@@ -64,38 +73,60 @@ jobs:
 
       - id: install_nix
         name: "Install Nix ❄️"
-        uses: cachix/install-nix-action@v26
+        uses: cachix/install-nix-action@v30
+        with:
+          github_access_token: ${{ secrets.GITHUB_TOKEN }}
+          enable_kvm: true
 
       - id: cachix
         name: "Enable Cachix ❄️"
-        uses: cachix/cachix-action@v14
+        uses: cachix/cachix-action@v15
+        if: vars.CACHIX_CACHE_NAME != ''
         with:
           name: ${{ vars.CACHIX_CACHE_NAME }}
           authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
-          useDaemon: false
+          useDaemon: true
           skipPush: false
 
-      - id: configure_nix
-        name: Configure Nix
+      - id: cache
+        name: Magic Nix cache
+        uses: DeterminateSystems/magic-nix-cache-action@main
+
+      - id: devenv_install
+        name: Devenv install
+        run: |
+          nix profile install --accept-flake-config nixpkgs#devenv
+
+      - id: devenv_gc
+        name: Devenv gc
+        run: |
+          devenv gc
+
+      - id: devenv_test
+        name: Devenv test
+        run: |
+          devenv test
+
+      - id: devenv_status
+        name: Devenv (status)
+        if: always()
+        shell: devenv shell --quiet bash -- -e {0}
         env:
-          NIX_CONFIG_HOME: "~/.config/nix"
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          mkdir -p "$NIX_CONFIG_HOME"
-          cat <<- EOF >> "$NIX_CONFIG_HOME/nix.conf"
-          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
-          EOF
-
-      - id: install_devenv
-        name: Install devenv
-        run: |
-          nix profile install --accept-flake-config tarball+https://install.devenv.sh/latest
-
-      - id: devenv_ci
-        name: Devenv CI
-        run: |
-          devenv ci
-
-      - id: devenv_shell
-        name: Devenv Shell
-        run: |
-          devenv shell echo "Development environment OK!"
+          if [[ ${{ steps.devenv_test.outcome }} == 'success' ]];
+          then
+            RESULT="success"
+            DESCRIPTION="Devenv test passed"
+          else
+            RESULT="failure"
+            DESCRIPTION="Devenv test failed"
+          fi
+          gh api \
+            repos/${{ github.repository }}/statuses/${{ github.sha }} \
+            -f state=${RESULT} \
+            -f context="${{ github.workflow }}" \
+            -f description="${DESCRIPTION}" \
+            -f target_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" || {
+              echo "Failed to report devenv status"; exit 1;
+            }
